### ISSUE TITLE
ChannelPresenter.unreadCount includes current user's sent messages

### ISSUE THREAD

**Issue by rpekarek** [GetStream/stream-chat-swift-demo#2]
The `unreadCount` property on `ChannelPresenter` seems to include messages sent by the current user when the user closes out the app and re-enters, but not when moving from the `DemoChatViewController` to the Channels `ViewController` after sending the initial message. I think the expected behavior would be for that value to never include messages sent by the current user.

**Comment by tbarbugli** [comment]
@rpekarek that's indeed the expected behavior, own messages should not be counted as unread @buh can you have a look into this?

**Comment by buh** [comment]
Sure, I'll check.

**Comment by buh** [comment]
@rpekarek I think it was fixed. Please check the latest version StreamChat v.1.0.5. The branch `custom-channel` 25b88cf
