### ISSUE TITLE
Need to customize both ChannelsViewController and ChatViewController

### ISSUE THREAD

**Issue by rpekarek** [GetStream/stream-chat-swift-demo#3]
I want to create custom classes that extend from ChannelsViewController and ChatViewController but there doesn't seem to be an easy way to override ` open func createChatViewController(at row: Int) -> ChatViewController?` since the `items` property in `ChannelsViewController` has an internal protection level and is inaccessible outside of the StreamChat pod. Is there a better way to do this?

**Comment by buh** [comment]
Hi @rpekarek. Please check the latest v.1.0.6
