### ISSUE TITLE
Error: Filter is a let constant

### ISSUE THREAD

**Issue by Edhoru** [GetStream/stream-chat-swift-demo#4]
When building the demo I get this error `Cannot assign to property: 'filter' is a 'let' constant` in line 26 of AppDelegate, the same error is in the documentation.
![image](https://user-images.githubusercontent.com/2679333/66243331-d782cf80-e6c9-11e9-8e56-2e0926959411.png)

**Comment by buh** [comment]
Hi @Edhoru. Yes, API changed, the filter should be in the `ChannelsPresenter.init`. We'll fix it.

**Comment by buh** [comment]
Fixed. We'll update tutorial soon.
