### ISSUE TITLE
Error with unreadCount

### ISSUE THREAD

**Issue by Edhoru** [GetStream/stream-chat-swift-demo#5]
When building the demo I get this error `Value of type 'ChannelPresenter' has no member 'unreadCount'` in line 30 of ViewController.
![image](https://user-images.githubusercontent.com/2679333/66243458-5972f880-e6ca-11e9-90f0-d2e4370c9d3a.png)

**Comment by buh** [comment]
Hi @Edhoru, thanks!
Yes, API changed https://getstream.io/chat/docs/swift/#unread
We'll fix it.

**Comment by buh** [comment]
Fixed. We'll update tutorial soon.
