### ISSUE TITLE
unreadCount property is not available anymore

### ISSUE THREAD

**Issue by DanielReyesDev** [GetStream/stream-chat-swift-demo#6]
`unreadCount` property of `ChannelPresenter` is not available anymore with the latest version of the Pod (StreamChat v1.3.21). Is there any other approach to get the same result?

Thanks in advance

**Comment by buh** [comment]
Thanks @DanielReyesDev! We'll fix it soon.
API changed https://getstream.io/chat/docs/swift/#unread

**Comment by buh** [comment]
Fixed. We'll update tutorial soon.
